### ISSUE TITLE
could not broadcast input array from shape error

### ISSUE THREAD

**Issue by Liampour** [SamirMitha/Denoising#1]
Hello, when I am trying to run the `FFDNet-Keras/test.py` for an image with dimensions 2564x1516 the following error appears 

Traceback (most recent call last):
  File "test.py", line 35, in <module>
    x = ffdnet_struct(x)
  File "/home/username/Denoising/FFDNet-Keras/utils.py", line 276, in ffdnet_struct
    ffdnetstruct[:, :, 0:12] = downsampled_images
ValueError: could not broadcast input array from shape (758,1282,12) into shape (25,25,12)

The code is working only for an image with dimensions 50x50.

Any recommendations?

**Comment by SamirMitha** [comment]
Hi, in the FFDNet folder there is a utils.py with functions to split images into 50x50 patches and reassemble them after they are denoised. You'll likely need to edit this code as all the paths are hardcoded.

**Comment by SamirMitha** [comment]
Try using evaluate.py

**Comment by Liampour** [comment]
Thanks evaluate.py works! But the resulting image consists of many squares.

![Capture](https://github.com/user-attachments/assets/042f0eea-56a9-4d7d-92e7-ba1cf043b183)

**Comment by SamirMitha** [comment]
Yea, that's expected due to kernel size and padding method. The edge pixels get messed up due to the padding. Theoretically if you break the image up into more patches that overlap with each other and merge the results accordingly, there would be no defined edges of each patch like you're seeing here. But doing that was outside the scope of this project.
